version: "3.3"
services:
  webapp:
    image: containous/whoami:v1.3.0
    labels:
      - "traefik.http.routers.whoami.rule=Host(`web.infraju.xyz`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.docker.network=proxy"
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.tls=true"
      - "traefik.http.routers.whoami.tls.certresolver=letsencrypt"
    networks:
     - proxy

networks:
  proxy:
#   name: proxy
             external: true
 
